vlib work
vlib activehdl

vlib activehdl/xil_defaultlib
vlib activehdl/xpm
vlib activehdl/axi_infrastructure_v1_1_0
vlib activehdl/smartconnect_v1_0
vlib activehdl/axi_protocol_checker_v2_0_1
vlib activehdl/axi_vip_v1_1_1
vlib activehdl/processing_system7_vip_v1_0_3
vlib activehdl/lib_pkg_v1_0_2
vlib activehdl/fifo_generator_v13_2_1
vlib activehdl/lib_fifo_v1_0_10
vlib activehdl/lib_srl_fifo_v1_0_2
vlib activehdl/lib_cdc_v1_0_2
vlib activehdl/axi_datamover_v5_1_17
vlib activehdl/axi_sg_v4_1_8
vlib activehdl/axi_dma_v7_1_16
vlib activehdl/axis_infrastructure_v1_1_0
vlib activehdl/axis_data_fifo_v1_1_16
vlib activehdl/xlconstant_v1_1_3
vlib activehdl/proc_sys_reset_v5_0_12
vlib activehdl/xlconcat_v2_1_1
vlib activehdl/gigantic_mux
vlib activehdl/generic_baseblocks_v2_1_0
vlib activehdl/axi_data_fifo_v2_1_14
vlib activehdl/axi_register_slice_v2_1_15
vlib activehdl/axi_protocol_converter_v2_1_15

vmap xil_defaultlib activehdl/xil_defaultlib
vmap xpm activehdl/xpm
vmap axi_infrastructure_v1_1_0 activehdl/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 activehdl/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_1 activehdl/axi_protocol_checker_v2_0_1
vmap axi_vip_v1_1_1 activehdl/axi_vip_v1_1_1
vmap processing_system7_vip_v1_0_3 activehdl/processing_system7_vip_v1_0_3
vmap lib_pkg_v1_0_2 activehdl/lib_pkg_v1_0_2
vmap fifo_generator_v13_2_1 activehdl/fifo_generator_v13_2_1
vmap lib_fifo_v1_0_10 activehdl/lib_fifo_v1_0_10
vmap lib_srl_fifo_v1_0_2 activehdl/lib_srl_fifo_v1_0_2
vmap lib_cdc_v1_0_2 activehdl/lib_cdc_v1_0_2
vmap axi_datamover_v5_1_17 activehdl/axi_datamover_v5_1_17
vmap axi_sg_v4_1_8 activehdl/axi_sg_v4_1_8
vmap axi_dma_v7_1_16 activehdl/axi_dma_v7_1_16
vmap axis_infrastructure_v1_1_0 activehdl/axis_infrastructure_v1_1_0
vmap axis_data_fifo_v1_1_16 activehdl/axis_data_fifo_v1_1_16
vmap xlconstant_v1_1_3 activehdl/xlconstant_v1_1_3
vmap proc_sys_reset_v5_0_12 activehdl/proc_sys_reset_v5_0_12
vmap xlconcat_v2_1_1 activehdl/xlconcat_v2_1_1
vmap gigantic_mux activehdl/gigantic_mux
vmap generic_baseblocks_v2_1_0 activehdl/generic_baseblocks_v2_1_0
vmap axi_data_fifo_v2_1_14 activehdl/axi_data_fifo_v2_1_14
vmap axi_register_slice_v2_1_15 activehdl/axi_register_slice_v2_1_15
vmap axi_protocol_converter_v2_1_15 activehdl/axi_protocol_converter_v2_1_15

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"E:/Xilinx_Vivado/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"E:/Xilinx_Vivado/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"E:/Xilinx_Vivado/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"E:/Xilinx_Vivado/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_1  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_1  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_3  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_processing_system7_0_0/sim/AXI_DMA_PL_PS_processing_system7_0_0.v" \

vcom -work lib_pkg_v1_0_2 -93 \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_1  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_1 -93 \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_1  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_10 -93 \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/f10a/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2 -93 \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_17 -93 \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/71f3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_8 -93 \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/5f94/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_16 -93 \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/bf8c/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_dma_0_0/sim/AXI_DMA_PL_PS_axi_dma_0_0.vhd" \

vlog -work axis_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_data_fifo_v1_1_16  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e3dd/hdl/axis_data_fifo_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axis_data_fifo_0_0/sim/AXI_DMA_PL_PS_axis_data_fifo_0_0.v" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axis_data_fifo_1_0/sim/AXI_DMA_PL_PS_axis_data_fifo_1_0.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/786b/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_10/sim/bd_f8a2_s00a2s_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_16/sim/bd_f8a2_s01a2s_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/92d2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_20/sim/bd_f8a2_m00s2a_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/258c/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_26/sim/bd_f8a2_m00e_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_21/sim/bd_f8a2_m00arn_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_22/sim/bd_f8a2_m00rn_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_23/sim/bd_f8a2_m00awn_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_24/sim/bd_f8a2_m00wn_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_25/sim/bd_f8a2_m00bn_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_17/sim/bd_f8a2_sawn_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_18/sim/bd_f8a2_swn_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_19/sim/bd_f8a2_sbn_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/8ad6/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_13/sim/bd_f8a2_s01mmu_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0f5f/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_14/sim/bd_f8a2_s01tr_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/925a/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_15/sim/bd_f8a2_s01sic_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_11/sim/bd_f8a2_sarn_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_12/sim/bd_f8a2_srn_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_7/sim/bd_f8a2_s00mmu_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_8/sim/bd_f8a2_s00tr_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_9/sim/bd_f8a2_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1b0c/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_2/sim/bd_f8a2_arsw_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_3/sim/bd_f8a2_rsw_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_4/sim/bd_f8a2_awsw_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_5/sim/bd_f8a2_wsw_0.sv" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_6/sim/bd_f8a2_bsw_0.sv" \

vlog -work xlconstant_v1_1_3  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_0/sim/bd_f8a2_one_0.v" \

vcom -work proc_sys_reset_v5_0_12 -93 \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/ip/ip_1/sim/bd_f8a2_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/bd_0/sim/bd_f8a2.v" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/sim/AXI_DMA_PL_PS_axi_smc_0.v" \

vcom -work xil_defaultlib -93 \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_rst_ps7_0_100M_0/sim/AXI_DMA_PL_PS_rst_ps7_0_100M_0.vhd" \

vlog -work xlconcat_v2_1_1  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_xlconcat_0_0/sim/AXI_DMA_PL_PS_xlconcat_0_0.v" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_system_ila_0_2/bd_0/ip/ip_0/sim/bd_8b20_ila_lib_0.v" \

vlog -work gigantic_mux  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/d322/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_system_ila_0_2/bd_0/ip/ip_1/bd_8b20_g_inst_0_gigantic_mux.v" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_system_ila_0_2/bd_0/ip/ip_1/sim/bd_8b20_g_inst_0.v" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_system_ila_0_2/bd_0/sim/bd_8b20.v" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_system_ila_0_2/sim/AXI_DMA_PL_PS_system_ila_0_2.v" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_system_ila_1_1/bd_0/ip/ip_0/sim/bd_4a31_ila_lib_0.v" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_system_ila_1_1/bd_0/ip/ip_1/bd_4a31_g_inst_0_gigantic_mux.v" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_system_ila_1_1/bd_0/ip/ip_1/sim/bd_4a31_g_inst_0.v" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_system_ila_1_1/bd_0/sim/bd_4a31.v" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_system_ila_1_1/sim/AXI_DMA_PL_PS_system_ila_1_1.v" \

vlog -work generic_baseblocks_v2_1_0  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_14  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_15  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_protocol_converter_v2_1_15  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/ec67/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/02c8/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/1313/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/0ab1/hdl" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/e2dd/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6180/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/a08d/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/6851/hdl/verilog" "+incdir+../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ipshared/82bb/hdl/verilog" "+incdir+E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_auto_pc_0/sim/AXI_DMA_PL_PS_auto_pc_0.v" \
"../../../../AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/sim/AXI_DMA_PL_PS.v" \

vlog -work xil_defaultlib \
"glbl.v"

