# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AXI_DMA_LOOP/AXI_DMA_LOOP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LOOP || ORIG_REF_NAME==AXI_DMA_LOOP} -quiet] -quiet

# IP: bd/AXI_DMA_LOOP/ip/AXI_DMA_LOOP_axi_dma_0_0/AXI_DMA_LOOP_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LOOP_axi_dma_0_0 || ORIG_REF_NAME==AXI_DMA_LOOP_axi_dma_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_LOOP/ip/AXI_DMA_LOOP_processing_system7_0_0/AXI_DMA_LOOP_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LOOP_processing_system7_0_0 || ORIG_REF_NAME==AXI_DMA_LOOP_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_LOOP/ip/AXI_DMA_LOOP_axis_data_fifo_0_0/AXI_DMA_LOOP_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LOOP_axis_data_fifo_0_0 || ORIG_REF_NAME==AXI_DMA_LOOP_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_LOOP/ip/AXI_DMA_LOOP_ps7_0_axi_periph_0/AXI_DMA_LOOP_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LOOP_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_DMA_LOOP_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_DMA_LOOP/ip/AXI_DMA_LOOP_rst_ps7_0_100M_0/AXI_DMA_LOOP_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LOOP_rst_ps7_0_100M_0 || ORIG_REF_NAME==AXI_DMA_LOOP_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/AXI_DMA_LOOP/ip/AXI_DMA_LOOP_axi_smc_0/AXI_DMA_LOOP_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LOOP_axi_smc_0 || ORIG_REF_NAME==AXI_DMA_LOOP_axi_smc_0} -quiet] -quiet

# IP: bd/AXI_DMA_LOOP/ip/AXI_DMA_LOOP_ila_0_0/AXI_DMA_LOOP_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LOOP_ila_0_0 || ORIG_REF_NAME==AXI_DMA_LOOP_ila_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_LOOP/ip/AXI_DMA_LOOP_system_ila_0_0/AXI_DMA_LOOP_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LOOP_system_ila_0_0 || ORIG_REF_NAME==AXI_DMA_LOOP_system_ila_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_LOOP/ip/AXI_DMA_LOOP_xlconcat_0_0/AXI_DMA_LOOP_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LOOP_xlconcat_0_0 || ORIG_REF_NAME==AXI_DMA_LOOP_xlconcat_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_LOOP/ip/AXI_DMA_LOOP_auto_pc_0/AXI_DMA_LOOP_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LOOP_auto_pc_0 || ORIG_REF_NAME==AXI_DMA_LOOP_auto_pc_0} -quiet] -quiet

# XDC: bd/AXI_DMA_LOOP/AXI_DMA_LOOP_ooc.xdc
