#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : AXI_DMA_LWIP.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Mar 04 23:32:13 +0800 2019
# SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved. 
#
# usage: AXI_DMA_LWIP.sh [-help]
# usage: AXI_DMA_LWIP.sh [-lib_map_path]
# usage: AXI_DMA_LWIP.sh [-noclean_files]
# usage: AXI_DMA_LWIP.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'AXI_DMA_LWIP.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_1 axi_vip_v1_1_1 processing_system7_vip_v1_0_3 lib_pkg_v1_0_2 fifo_generator_v13_2_1 lib_fifo_v1_0_10 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_17 axi_sg_v4_1_8 axi_dma_v7_1_16 axis_infrastructure_v1_1_0 axis_data_fifo_v1_1_16 xlconstant_v1_1_3 proc_sys_reset_v5_0_12 gigantic_mux generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_14 axi_register_slice_v2_1_15 axi_protocol_converter_v2_1_15)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "AXI_DMA_LWIP.sh - Script generated by export_simulation (Vivado v2017.4 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "E:/Xilinx_Vivado/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "E:/Xilinx_Vivado/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "E:/Xilinx_Vivado/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "E:/Xilinx_Vivado/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_processing_system7_0_0/sim/AXI_DMA_LWIP_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_1 $vhdlan_opts \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/f10a/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_17 $vhdlan_opts \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/71f3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_8 $vhdlan_opts \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/5f94/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_16 $vhdlan_opts \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/bf8c/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_dma_0_0/sim/AXI_DMA_LWIP_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v1_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e3dd/hdl/axis_data_fifo_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axis_data_fifo_0_0/sim/AXI_DMA_LWIP_axis_data_fifo_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/786b/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/bd_0/ip/ip_5/sim/bd_bd24_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/92d2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/bd_0/ip/ip_9/sim/bd_bd24_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/258c/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/bd_0/ip/ip_10/sim/bd_bd24_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/bd_0/ip/ip_6/sim/bd_bd24_sawn_0.sv" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/bd_0/ip/ip_7/sim/bd_bd24_swn_0.sv" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/bd_0/ip/ip_8/sim/bd_bd24_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/8ad6/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/bd_0/ip/ip_2/sim/bd_bd24_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0f5f/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/bd_0/ip/ip_3/sim/bd_bd24_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/925a/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/bd_0/ip/ip_4/sim/bd_bd24_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/bd_0/ip/ip_0/sim/bd_bd24_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/bd_0/ip/ip_1/sim/bd_bd24_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/bd_0/sim/bd_bd24.v" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/sim/AXI_DMA_LWIP_axi_smc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_rst_ps7_0_100M_0/sim/AXI_DMA_LWIP_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_system_ila_0_0/bd_0/ip/ip_0/sim/bd_983d_ila_lib_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gigantic_mux $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/d322/hdl/gigantic_mux_v1_0_cntr.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_system_ila_0_0/bd_0/ip/ip_1/bd_983d_g_inst_0_gigantic_mux.v" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_system_ila_0_0/bd_0/ip/ip_1/sim/bd_983d_g_inst_0.v" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_system_ila_0_0/bd_0/sim/bd_983d.v" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_system_ila_0_0/sim/AXI_DMA_LWIP_system_ila_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ipshared/82bb/hdl/verilog" +incdir+"E:/Xilinx_Vivado/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_auto_pc_0/sim/AXI_DMA_LWIP_auto_pc_0.v" \
    "$ref_dir/../../../../AXI_DMA_LWIP.srcs/sources_1/bd/AXI_DMA_LWIP/sim/AXI_DMA_LWIP.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.AXI_DMA_LWIP xil_defaultlib.glbl -o AXI_DMA_LWIP_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./AXI_DMA_LWIP_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./AXI_DMA_LWIP.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key AXI_DMA_LWIP_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc AXI_DMA_LWIP_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./AXI_DMA_LWIP.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: AXI_DMA_LWIP.sh [-help]\n\
Usage: AXI_DMA_LWIP.sh [-lib_map_path]\n\
Usage: AXI_DMA_LWIP.sh [-reset_run]\n\
Usage: AXI_DMA_LWIP.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
