# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AXI_DMA_LWIP/AXI_DMA_LWIP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LWIP || ORIG_REF_NAME==AXI_DMA_LWIP} -quiet] -quiet

# IP: bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_processing_system7_0_0/AXI_DMA_LWIP_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LWIP_processing_system7_0_0 || ORIG_REF_NAME==AXI_DMA_LWIP_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_dma_0_0/AXI_DMA_LWIP_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LWIP_axi_dma_0_0 || ORIG_REF_NAME==AXI_DMA_LWIP_axi_dma_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axis_data_fifo_0_0/AXI_DMA_LWIP_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LWIP_axis_data_fifo_0_0 || ORIG_REF_NAME==AXI_DMA_LWIP_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_axi_smc_0/AXI_DMA_LWIP_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LWIP_axi_smc_0 || ORIG_REF_NAME==AXI_DMA_LWIP_axi_smc_0} -quiet] -quiet

# IP: bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_rst_ps7_0_100M_0/AXI_DMA_LWIP_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LWIP_rst_ps7_0_100M_0 || ORIG_REF_NAME==AXI_DMA_LWIP_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_ps7_0_axi_periph_0/AXI_DMA_LWIP_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LWIP_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_DMA_LWIP_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_system_ila_0_0/AXI_DMA_LWIP_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LWIP_system_ila_0_0 || ORIG_REF_NAME==AXI_DMA_LWIP_system_ila_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_LWIP/ip/AXI_DMA_LWIP_auto_pc_0/AXI_DMA_LWIP_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_LWIP_auto_pc_0 || ORIG_REF_NAME==AXI_DMA_LWIP_auto_pc_0} -quiet] -quiet

# XDC: bd/AXI_DMA_LWIP/AXI_DMA_LWIP_ooc.xdc
