# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AXI_DMA_PL_PS/AXI_DMA_PL_PS.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_PL_PS || ORIG_REF_NAME==AXI_DMA_PL_PS} -quiet] -quiet

# IP: bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_processing_system7_0_0/AXI_DMA_PL_PS_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_PL_PS_processing_system7_0_0 || ORIG_REF_NAME==AXI_DMA_PL_PS_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_dma_0_0/AXI_DMA_PL_PS_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_PL_PS_axi_dma_0_0 || ORIG_REF_NAME==AXI_DMA_PL_PS_axi_dma_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_PL_PS_axis_data_fifo_0_0 || ORIG_REF_NAME==AXI_DMA_PL_PS_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axis_data_fifo_1_0/AXI_DMA_PL_PS_axis_data_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_PL_PS_axis_data_fifo_1_0 || ORIG_REF_NAME==AXI_DMA_PL_PS_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axi_smc_0/AXI_DMA_PL_PS_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_PL_PS_axi_smc_0 || ORIG_REF_NAME==AXI_DMA_PL_PS_axi_smc_0} -quiet] -quiet

# IP: bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_rst_ps7_0_100M_0/AXI_DMA_PL_PS_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_PL_PS_rst_ps7_0_100M_0 || ORIG_REF_NAME==AXI_DMA_PL_PS_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_ps7_0_axi_periph_0/AXI_DMA_PL_PS_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_PL_PS_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_DMA_PL_PS_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_xlconcat_0_0/AXI_DMA_PL_PS_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_PL_PS_xlconcat_0_0 || ORIG_REF_NAME==AXI_DMA_PL_PS_xlconcat_0_0} -quiet] -quiet

# IP: bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_system_ila_0_2/AXI_DMA_PL_PS_system_ila_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_PL_PS_system_ila_0_2 || ORIG_REF_NAME==AXI_DMA_PL_PS_system_ila_0_2} -quiet] -quiet

# IP: bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_system_ila_1_1/AXI_DMA_PL_PS_system_ila_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_PL_PS_system_ila_1_1 || ORIG_REF_NAME==AXI_DMA_PL_PS_system_ila_1_1} -quiet] -quiet

# IP: bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_auto_pc_0/AXI_DMA_PL_PS_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DMA_PL_PS_auto_pc_0 || ORIG_REF_NAME==AXI_DMA_PL_PS_auto_pc_0} -quiet] -quiet

# XDC: bd/AXI_DMA_PL_PS/AXI_DMA_PL_PS_ooc.xdc
