# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/ZYNQ7020/FPGA_EXAMPLE/AXI_DMA_PL_PS/AXI_DMA_PL_PS/AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0.xci
# IP: The module: 'AXI_DMA_PL_PS_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ZYNQ7020/FPGA_EXAMPLE/AXI_DMA_PL_PS/AXI_DMA_PL_PS/AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_DMA_PL_PS_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/ZYNQ7020/FPGA_EXAMPLE/AXI_DMA_PL_PS/AXI_DMA_PL_PS/AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_DMA_PL_PS_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/ZYNQ7020/FPGA_EXAMPLE/AXI_DMA_PL_PS/AXI_DMA_PL_PS/AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_DMA_PL_PS_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/ZYNQ7020/FPGA_EXAMPLE/AXI_DMA_PL_PS/AXI_DMA_PL_PS/AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0.xci
# IP: The module: 'AXI_DMA_PL_PS_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ZYNQ7020/FPGA_EXAMPLE/AXI_DMA_PL_PS/AXI_DMA_PL_PS/AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_DMA_PL_PS_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/ZYNQ7020/FPGA_EXAMPLE/AXI_DMA_PL_PS/AXI_DMA_PL_PS/AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_DMA_PL_PS_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/ZYNQ7020/FPGA_EXAMPLE/AXI_DMA_PL_PS/AXI_DMA_PL_PS/AXI_DMA_PL_PS.srcs/sources_1/bd/AXI_DMA_PL_PS/ip/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0/AXI_DMA_PL_PS_axis_data_fifo_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_DMA_PL_PS_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
